### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by muqeet98** [talsec/Free-RASP-Android#10]
I am unable to Integrate this in React Native. Is it possible to use in React Native Application?

**Comment by syakymchuk** [comment]
Hello @muqeet98 , 

We have customers that successfully integrated Talsec into React Native apps. Could you please provide more detailed information about what you do and what problems you encounter? Feel free to make a video recording.   

Have a great day!

**Comment by muqeet98** [comment]
> Hello @muqeet98 ,
> 
> We have customers that successfully integrated Talsec into React Native apps. Could you please provide more detailed information about what you do and what problems you encounter? Feel free to make a video recording.
> 
> Have a great day!

**Comment by muqeet98** [comment]
> > Hello @muqeet98 ,
> > We have customers that successfully integrated Talsec into React Native apps. Could you please provide more detailed information about what you do and what problems you encounter? Feel free to make a video recording.
> > Have a great day!
@syakymchuk Can you please share any docs for React Native Apps? Android and IOS both.

**Comment by muqeet98** [comment]
@syakymchuk  Can you please share any docs for React Native Apps? Android and IOS both.

**Comment by muqeet98** [comment]
Not Solved

**Comment by muqeet98** [comment]
@syakymchuk Getting this error When I put the maven url in build.gradle.
`> Could not get resource 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom'.
            > Could not HEAD 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom'.`

**Comment by talsec-app** [comment]
Hi @muqeet98 ,
Could you please share the gradle file with us? Ensure that you are only adding our nexus repositories to the list and that the `mavenCentral()` and `google()` are still available on the list.

Best regards,
Talsec Team

**Comment by syakymchuk** [comment]
> @syakymchuk Can you please share any docs for React Native Apps? Android and IOS both.

@muqeet98 , the documentation for React integration is not ready yet. This is the reason why we are not claiming the support of React Native officially. Though we would be happy to help you to pass through the integration process. You are more than welcome support / contribute #freeRASP with drafting your integration guideline, self-check list, and issues that you have experienced. Thank you in advance!

**Comment by muqeet98** [comment]
> Hi @muqeet98 , Could you please share the gradle file with us? Ensure that you are only adding our nexus repositories to the list and that the `mavenCentral()` and `google()` are still available on the list.
> 
> Best regards, Talsec Team

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
    }
    ext.kotlin_version = '1.5.21'
    repositories {
        google()
        jcenter()

        // gradlePluginPortal()
    }
    
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.2")
        classpath 'com.google.gms:google-services:4.3.14'
        // classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        // jcenter()

        mavenLocal()
            maven { url "[https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp]" }

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
            maven {
      url "https://cashshield-sdk.s3.amazonaws.com/release/"
    }



        // gradlePluginPortal()
        jcenter()

        // maven { url 'https://dl.bintray.com/ironsource-mobile/android-sdk' }
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
        //  maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
        // maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
    }
}
`

**Comment by talsec-app** [comment]
We suspect that the issue is with the jcenter repository which is no longer supported. From the log you sent, you can see that the dependency `com.facebook.fresco:imagepipeline-native` cannot be found. Also, there is no version `2.2.0` available. 
We do not use this dependency in our project, so the issue should still remain even if you comment our repository out. 

There is a version `2.3.0` available on `mavenCentral()` ([here](https://mvnrepository.com/artifact/com.facebook.fresco/imagepipeline-native/2.3.0)), but you need to update the repositories (add `mavenCentral()` right bellow `google()`) and increase the version of `com.facebook.fresco:imagepipeline-native`. 

Let us know, if it helped.
