### ISSUE TITLE
Cannot Access the Library. Received Status Code 521 from Server

### ISSUE THREAD

**Issue by andikaputraputu22** [talsec/Free-RASP-Android#12]
Hi,

I tried following the instructions in [Free-RASP-Android](https://github.com/talsec/Free-RASP-Android)
But, when I rebuild the project, I got an error on build output:

```Could not HEAD 'https://jitpack.io/com/aheaditec/talsec/security/TalsecSecurity-Community/4.2.1-dev/TalsecSecurity-Community-4.2.1-dev.pom'. Received status code 521 from server```

Here is my project's ```build.gradle```:

```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.google.com/" }
        maven { url 'https://jitpack.io' }
        maven { url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp" }
        maven { url "https://developer.huawei.com/repo/" }
    }
}
```

Here is my app ```build.gradle```:
```
releaseImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:4.2.1-release'
debugImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:4.2.1-dev'
```

Is there an issue with my implementation? Or is there a problem with the library?

Maybe there is a hint to resolve this issue.

Thank you.

**Comment by talsec-app** [comment]
Hello @andikaputraputu22 , 
it could be related to temporary shutdown of the Nexus repo. Please try if you are able to access the following link: https://nexus3-public.monetplus.cz/#browse/browse:ahead-talsec-free-rasp
You can also try to place the freeRASP dependencies before:
`maven { url "https://maven.google.com/" }
        maven { url 'https://jitpack.io' }`

Kind regards,
Talsec team

**Comment by andikaputraputu22** [comment]
Hi @talsec-app

Previously, thank you for your response.
After I followed the intructions above, it's working properly now.

Thank you.
