### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by fanjavaid** [talsec/Free-RASP-Android#18]
Hello, I implemented the library version 6.0.0 and I got the following crashes:

- `Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.gbox.android/_root/data/internal_app/com.company.android-gep493u9x7yrZ9yoy5Lqtw==/lib/arm/libpolarssl.so" is 32-bit instead of 64-bit
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.aheaditec.talsec.security.z1.<clinit>(SourceFile:1)
       at com.aheaditec.talsec.security.y1.<init>(SourceFile:5)
       at com.aheaditec.talsec.security.y1.a(SourceFile:4)
       at com.aheaditec.talsec_security.security.api.Talsec.start(SourceFile:1)`

- `Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libpolarssl.so" not found`

When I check my universal APK, I have the `libpolarssl.so` both in x86 and x64. However I distribute the app as Bundle in the Google Play Console.

I had tried to add exception handler when called `at com.aheaditec.talsec_security.security.api.Talsec.start` but the crash still exist.

Is the Library for android support for x86? And any insight why the crash happens?

Thank you

**Comment by msikyna** [comment]
Hello @fanjavaid,

The library should support both x86 and x64. The library (aar) contains `libpolarssl.so` for all ABIs (x86, x86_64, armeabi-v7a, arm64-v8a). Can you check on which devices the crash occurs? Is it a general problem for all x64 devices, or it only occurs on some devices? You can also inspect your bundle file (.aab) if the `base/lib` directory contains libpolarssl.so for all ABIs. We will try to look into this issue but I’m not sure if we will be able to reproduce this issue.

Best regards,
Talsec Team

**Comment by fanjavaid** [comment]
Hello @msikyna 

Here is the details about the devices:

<img width="424" alt="Screenshot 2023-06-22 at 10 52 55" src="https://github.com/talsec/Free-RASP-Android/assets/866289/4d55a736-c188-4830-979e-3dfc616055e5">
<img width="426" alt="Screenshot 2023-06-22 at 10 52 47" src="https://github.com/talsec/Free-RASP-Android/assets/866289/c79603cb-f330-4346-935c-59cd40f3fbc0">

Well, the Bundle file contains for all ABIS : `x86_64, x86, arm64-v8a, armeabi-v7a`.
I can't reproduce the issue too.

Or do you have any suggestion how to handle it? I believe App crashes when invoke `Talsec.start()`, but I can't catch the Exception. Crash still exists.

Thank you

**Comment by rpavliuk** [comment]
We have, I guess, a similar issue:

`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.signnow.android-9yrhDsO0RpoyrWxEyG4MXA==/base.apk"],nativeLibraryDirectories=[/data/app/com.signnow.android-9yrhDsO0RpoyrWxEyG4MXA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libpolarssl.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.aheaditec.talsec.security.b2.<clinit>(SourceFile:1)
       at com.aheaditec.talsec.security.a2.<init>(SourceFile:6)
       at com.aheaditec.talsec.security.a2.a(SourceFile:4)
       at com.aheaditec.talsec_security.security.api.Talsec.start(SourceFile:1)
       at com.signnow.app.app.SignNowApp.setTalsecLibrary(SignNowApp.kt:128)
       at com.signnow.app.app.SignNowApp.onCreate(SignNowApp.kt:64)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

It is our first release with your library. At this time it occurred only on Nexus 5X devices. I have researched SO a bit and found a similar [issue](https://stackoverflow.com/q/27186726/2659925). I don't want to try the solution on my current users. Can you provide some information about this error?
Or maybe I can safely use this solution?

Also, I need to mention that I have this block in my `build.gradle` file. Because I have some native libraries:

```kotlin
ndk {
            abiFilters.addAll(
                listOf(
                    "arm64-v8a", "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
                )
            )
        }
```

**Comment by msikyna** [comment]
Hello @fanjavaid , @rpavliuk ,

we are looking at the issue. Thank you for details.

Kind regards,
Talsec team

**Comment by rpavliuk** [comment]
@msikyna Can we help you with framing this bug?

**Comment by xprikryl2** [comment]
Hello @fanjavaid,

We've managed to provide a partial solution. The native library `libpolarssl.so` is no longer required in the freeRASP workflow, so the bug mentioned above shouldn't occur anymore.

Nevertheless, there are still other native libraries that are crucial for freeRASP (`libsecurity.so` and `libclib.so`) that can also be problematic. I found a lot of open issues regarding this problem (eg. [Xiaomi native library load](https://issuetracker.google.com/issues/147096055), [App bundle UnsatisfiedLinkError](https://stackoverflow.com/questions/52595535/using-an-app-bundle-i-get-unsatisfiedlinkerror-for-1-of-users), [App Bundle native crash](https://bugreports.qt.io/browse/QTBUG-80766), and many others). It looks like there are still some issues during native library loading.

I also stumbled upon two proposed solutions, but I haven't had the possibility to test them out yet.
1. Disabling bundle ABI split in the `build.gradle` as described [here](https://developer.android.com/guide/app-bundle/configure-base#disable_config_apks). This will slightly increase the size of a bundle.
```
bundle {
    abi {
        // This property is set to true by default.
        enableSplit = false
    }
}
```
2. In the stack trace of this issue above, the application is trying to load a native library from the app directory in the filesystem. That usually means that the native libraries are compressed and extracted to the filesystem during the installation. You can try to modify your [extractNativeLibs]( https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) and If you’re using App Bundle, also set `android.bundle.enableUncompressedNativeLibs=true` along with the extractNativeLibs configuration option.
3. There is also a GH project [ReLinker](https://github.com/KeepSafe/ReLinker) that tries to solve issues with native libraries linking.


If you manage to try one of the proposed solutions above or if you find a new one, please share your findings with us.

Best regards,
Talsec Team

**Comment by rpavliuk** [comment]
Thank you so much, we will try to update your library and discuss the suggested solutions. 
I will update you after the release of our app

**Comment by rpavliuk** [comment]
After monitoring this crash for some time we can conclude that it happens more on Emulators or already Rooted devices. So, it is not affecting us, because we plan to block these devices anyway.
But after the update we have encountered a new crash. I have created a separate [issue](https://github.com/talsec/Free-RASP-Android/issues/24) for it.

**Comment by fanjavaid** [comment]
Hello, after releasing the updated version with workarounds above, the issue about `UnsatisfiedLinkError` was not happening. But, like @rpavliuk there is a new issue: `Fatal Exception: java.lang.RuntimeException: Package manager has died` in the latest Talsec version.

**Comment by msikyna** [comment]
Hello @rpavliuk , @fanjavaid , 
thank you for reporting the issue! We are looking into it.

Kind regards,
Talsec team
