### ISSUE TITLE
Fatal Exception: java.lang.SecurityException 

### ISSUE THREAD

**Issue by arshakavag92** [talsec/Free-RASP-Android#20]
I'm having an issue using Community version of the library

Fatal Exception: java.lang.SecurityException
Must have USE_BIOMETRIC permission: Neither user {userId} nor current process has android.permission.USE_BIOMETRIC.

Currently the app is not using any biometric verification in it, however, I'm having this issue on some devices with Android 12 and Android 13

SDK Version: 7.0.0

**Comment by xprikryl2** [comment]
Hi @arshakavag92,

I've managed to reproduce this issue. Permissions `USE_BIOMETRIC`, `USE_FINGERPRINT` should be merged automatically from your dependencies. If the permission merging is disabled, the SecurityException occurs. 

We're going to add a fix that will skip the biometric presence check if the permission is not declared in the manifest. The new release with this bug fix should be available soon. Thank you for reporting this bug. 

Best regards,
Talsec Team

**Comment by msikyna** [comment]
Hello @arshakavag92 ,
the issue has been solved in the new version: 8.0.4.

Kind regards,
Talsec team
