### ISSUE TITLE
The Nexus server is down

### ISSUE THREAD

**Issue by rongjc** [talsec/Free-RASP-Android#23]
Hi, I think the Nexus server is down, when I tried to build my project, I got this error
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community:8.0.2.
         > Could not get resource 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/aheaditec/talsec/security/TalsecSecurity-Community/8.0.2/TalsecSecurity-Community-8.0.2.pom'.
            > Could not GET 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/aheaditec/talsec/security/TalsecSecurity-Community/8.0.2/TalsecSecurity-Community-8.0.2.pom'.
               > Read timed out

Also this link is not accessible
https://nexus3-public.monetplus.cz/#browse/browse:ahead-talsec-free-rasp

**Comment by msikyna** [comment]
Hello @rongjc ,
the issue has been solved. The Nexus server is up again. We have a replacement of the server in the roadmap.

Kind regards,
Talsec team
