### ISSUE TITLE
Issue in building gradle dependency

### ISSUE THREAD

**Issue by UrmiBhanani** [talsec/Free-RASP-Android#28]
**Issue in building gradle dependency**
Gradle build not downloading dependency. I tried to open url in web its returning Error 400

**To Reproduce**
I integrate FreeRASPDemoApp but not able to sync and build. 

**Note:** The same demo app was working fine a few days back.

**Comment by msikyna** [comment]
Hello @UrmiBhanani ,

does the issue still occur? Thank you!

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Closing, if the issue will occur again, please reopen it.

Kind regards,
Talsec team

**Comment by a-raosaheb-gunjal** [comment]
@talsec-app @msikyna - getting this issue with 15.1.0

implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:15.1.0'
