### ISSUE TITLE
onPasscode Called in wrong scenario 

### ISSUE THREAD

**Issue by mdynia1** [talsec/Free-RASP-Android#29]
Even thought password is set on phone, onPasscode is called: 

 - Device: Xiaomi 13 T Pro
 - OS version: Android 14
 - Version of freeRASP:  6.3.0

**Comment by msikyna** [comment]
Hello @mdynia1 ,
thank you for reporting it, we will verify it.

Kind regards,
Talsec team

**Comment by xprikryl2** [comment]
Hello @mdynia1 , 

I double-checked the code, but I couldn't find any bug in our implementation. We're using the Android API call [isDeviceSecure](https://developer.android.com/reference/android/app/KeyguardManager#isDeviceSecure()), which checks if the PIN, pattern, or password is set. Could you please check the output of `isDeviceSecure()` method on your device?

Kind regards,
Talsec Team

**Comment by msikyna** [comment]
Hello @mdynia1 ,

could you check the output of isDeviceSecure()? Thank you!

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @mdynia1 ,
have you been able to check the output of isDeviceSecure()? Thank you!

Kind regards,
Talsec team
