### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by m-akbarfauzi** [talsec/Free-RASP-Android#35]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.1.0.
     Required by:
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.1.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.1.0/TalsecSecurity-Community-Flutter-9.1.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.1.0/TalsecSecurity-Community-Flutter-9.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by msikyna** [comment]
https://github.com/talsec/Free-RASP-Flutter/issues/118
