### ISSUE TITLE
Is mandatory to include "https://developer.huawei.com/repo/"

### ISSUE THREAD

**Issue by KKChong** [talsec/Free-RASP-Android#5]
Referring to the title matter, is mandatory to include "huawei HMS" to the project?

**Comment by talsec-app** [comment]
Hi @KKChong ,

Yes, it is necessary to include the Huawei repository in the project. We want to include as many checks as possible, including GMS SafetyNet and HMS SafetyDetect protections in the future. 

We understand that not all of the clients plan to use HMS. In the current version, you don't need to set up or configure any additional information in the Google Console or Huawei App Gallery, our library doesn't require any API key or configuration JSON files, you only need to include the Huawei repository. We plan to make all of those new features optional in the future, so you can enable only the checks you really want. 

We hope that this inconvenience is not crucial for you.

Best regards,
Talsec Team

**Comment by KKChong** [comment]
ok, understood. Thanks for clarification
