### ISSUE TITLE
Unable to detect noxplayer emulator

### ISSUE THREAD

**Issue by KKChong** [talsec/Free-RASP-Android#6]
I've tried to run the app on the Nox emulator. It seems like the SDK is not able to detect the nox emulator. Below is the system information of the emulator:

Nox version: 7.0.3.3033-9.0900220715
Android version: Android 9(64 bit)
System version: Windows10-64bit-4cpu
Computer model: MSI-MS-7850
CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
Total memory: 15.9 GB
Available memory: 10.0 GB
CPU VT: Enabled
Rendering mode: OpenGL+
OpenGL version: 4.3.0 - Build 20.19.15.4624
OpenGL rendering: Intel(R) HD Graphics 4600
Discrete graphics: Enabled
Graphics card1: Intel(R) HD Graphics 4600
Firewall: Enabled(Recommend to disable)
Installation path: D:\Program Files\Nox\bin
Log Path: C:\Users\KK\AppData\Local\Nox
Emulator disk space: total  128G, available 116G

**Comment by talsec-app** [comment]
Hello KKChong, 

you are right, the SDK is not yet able to detect the Nox emulator. The feature will be added in upcoming releases. Thank you!

Kind regards,
Talsec team

**Comment by talsec-app** [comment]
Hi @KKChong ,
We have great news! We will roll out a new freeRASP with improved emulator detection (including Nox). Stay tuned for new freeRASP release :) !
King regards,
Talsec Team

**Comment by msikyna** [comment]
Hello @KKChong ,

A new version (https://github.com/talsec/Free-RASP-Android/releases/tag/v6.0.0) has been released, which detects the Nox emulator.

Kind regards,
Matúš, Talsec developer
