### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shanlin2dltk** [talsec/Free-RASP-Android#7]
I follow your instruction on my cordova app.  When building, it generated error:
`> Task :app:dataBindingMergeDependencyArtifactsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.

> Could not resolve all files for configuration ':app:debugCompileClasspath'.

   > Could not find com.aheaditec.talsec.security:TalsecSecurity-Community:4.2.1-release.

     Required by:

         project :app

`
Could you let me know how to resolve this?

**Comment by talsec-app** [comment]
Hello @shanlin2dltk , we will investigate the issue and get back to you asap.

Kind regards,
Talsec team

**Comment by talsec-app** [comment]
Hello @shanlin2dltk,

The error you are getting informs you that the library/artifact `com.aheaditec.talsec.security:TalsecSecurity-Community:4.2.1-release` could not be found. This library/artifact is available on our self-hosted repository and that’s why you need to define the repository in your project.

For a typical native Android application, you can follow the instructions in [step 1](https://github.com/talsec/Free-RASP-Android#step-1-add-talsec-to-your-gradle) to add the repository into your project. You should add those two lines into your repositories list:

```groovy
[build.gradle (NameOfProject)]
...
allprojects {
  repositories {
    ...
    maven { url “https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp” }
    maven { url “https://developer.huawei.com/repo/” }
  }
}
```

or alternatively

```groovy
[settings.gradle (NameOfProject)]
...
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    ...
    maven { url “https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp” }
    maven { url “https://developer.huawei.com/repo/” }
  }
}
```

If you are using Cordovas [recommended `build-extras.gradle`](https://cordova.apache.org/docs/en/10.x/guide/platforms/android/#extending-buildgradle) file for `build.gradle` customization, you need to define freeRASP repositories as well.

If you are not able to solve the issue on your own, could you please provide your modified `.gradle` files to us? You can mail it to info@talsec.app 

Kind regards,
Talsec Team

**Comment by talsec-app** [comment]
Hello @shanlin2dltk ,

We would like to announce that the Talsec Cordova plugin will be available soon here on our Talsec GitHub. We've just finished the implementation phase of the plugin for both Android and iOS. We want to prepare a simple integration manual together with the demo application so you can easily try the solution. 

Kind regards,
Talsec Team
