### ISSUE TITLE
Able to recompile the APK

### ISSUE THREAD

**Issue by abhishekpalad** [talsec/Free-RASP-Android#8]
I am able to modify the manifest file (changed the backup to false ) and recompile the application. The application is getting successfully installed on the system..

**Comment by talsec-app** [comment]
Hello @abhishekpalad , 
First, we want to commend you for verifying the security features over blindly trusting! That's the way to go.
Second, we would like to understand better the steps you've taken so far. Usually, you should receive an onTamperDetected callback in such a case.
Thank you in advance
Talsec Team

**Comment by abhishekpalad** [comment]
Hi Team,

I build the app using Android Studio

then i just followed default steps to decompile the application using apktool v 2.6.4 and then recompiled it with different developer key (i have generated new keys) then used adb install with (-r -t ) to install the app.

I have attached the modified APK.
[app-debugTampered.zip](https://github.com/talsec/Free-RASP-Android/files/9837114/app-debugTampered.zip)

**Comment by talsec-app** [comment]
Hello @abhishekpalad ,
did the explanation helped?

Kind regards,
Talsec team
